.github/workflows/wiki.yml

Commited to wrong branch

---

docs/Events/Cargonia.md

I'm not sure if it will work, mostly just testing

Cargonia link fix (maybe)

---

docs/Events/Cargonia.md

maybe the links will work this time

trying again

---

docs/Items/Department Battery

Department Battery as Item, 
I have the Information from the Discord. I don't have rights to upload a picture, the power_setup.png is missing, anyone can help ?
The Picture is attached.

Department Battery

---

docs/Roles/Antagonist roles/Traitor.md

And some tips and tricks to being a good (and bad) traitor.

Update to PDA

---

docs/Roles/Antagonist roles/Traitor.md

just figured out its captain not caipaitain XD.

General fixes on typos

---

docs/Guides/General guides/How-not-to-die-instantly.md

Reordered the guide to fit better the average new players need and added some extra direction on things noobs can do to get better at the game. Removed some weird part about things flying and killing you (?) and added three sections on the "tutorial" (how to put on the oxigen mask), walking and running and basic directions on how to use the radio. Added some clues to the mentor help chat that is about to be implemented.

Major rewrite

---

docs/Items/High-Risk Items.md

It still lacks some minor risk items such as minor guns and other kinds of weaponry, but it has all of the traitor important items.

High risk items major rewrite (as requested)

---

docs/Guides/General guides/How-not-to-die-instantly.md

I think now it will look half decent, but idk.

Fixed format issue

---

docs/Guides/Service guides/Guide-to-Food-and-Cooking.md

This is my first try to help, english is not my native language so sorry for any grammtical mistakes, i tried my best hopefully. Wanted to teach cooks how to make dough and use a bowl.

A small update on how to use a bowl.

---

docs/Guides/Engineering guides/Guide-to-the-nuclear-reactor.md

Added some hierarchy to the headers and fixed a unicode musical note that didn't display properly on any of my devices.

Patch to the Guide to the nuclear reactor

---

docs/Roles/Antagonist roles/Traitor.md

the wiki says that most stuff dosent work, but because it now does, i thought we should fix it

correcting info about functionality for trator wiki

---

docs/Roles/Antagonist roles/Traitor.md

removed the line about functionality as it was unnececary

updating the wiki again

---

docs/Roles/Cargo roles/Shaft-Miner.md

This PR accomplishes the first 4 tasks of #64.

Updated shaft miner with ORM, box, vendor,

---

docs/Roles/Antagonist roles/Nuclear Operative.md

updated nuclear operative page with new options

---

docs/Guides/Engineering guides/Hacking-Guide.md

Now it matches up with new hacking.

Update hacking guide.

---

docs/Items/Syndicate Items.md

Add the new items that have been added, remove the blood red magboots as it seems that they have been removed.

Update traitor items list.

---

docs/Roles/Ghost roles/Ashwalker.md

Adds simple file for ashwalker ghost role.

Adds simple file for ashwalker ghost role.

---

docs/Roles/Cargo roles/Shaft-Miner.md

Defined tips and tricks section
Added casino side mission

Tips and casinos

---

docs/Roles/Service roles/Mime.md

Add mime spells to mime job description.

---

docs/Guides/Medical guides/Surgery.md

Very basic guide to surgery,

---

docs/Items/Syndicate Items.md

Updates syndicate items page to include explosive devices
